const allmarks = [  {name:"luxgen"},
                    {name:"hyundai"},
                    {name:"peugeot"},
                    {name:"mazda"},
                    {name:"mercedes-benz"},
                    {name:"chery"},
                    {name:"plymouth"},
                    {name:"byd"},
                    {name:"saab"},
                    {name:"луаз"},
                    {name:"citroen"},
                    {name: "lifan"},
                    {name: "газ"},
                    {name: "зил"},
                    {name: "lexus"},
                    {name: "toyota"},
                    {name: "заз"},
                    {name: "alfa romeo"},
                    {name: "acura"},
                    {name: "lancia"},
                    {name: "honda"},
                    {name: "cadillac"},
                    {name: "proton"},
                    {name: "isuzu"},
                    {name: "seat"},
                    {name: "lincoln"},
                    {name: "уаз"},
                    {name: "bmw"},
                    {name: "тагаз"},
                    {name: "daewoo"},
                    {name: "great wall"},
                    {name: "mitsubishi"},
                    {name: "geely"},
                    {name: "mercury"},
                    {name: "infiniti"},
                    {name: "morris"},
                    {name: "faw"},
                    {name: "dacia"},
                    {name:"porsche"},
                    {name: "subaru"},
                    {name: "haima"},
                    {name: "jeep"},
                    {name: "pontiac"},
                    {name: "chevrolet"},
                    {name: "volkswagen"},
                    {name: "daihatsu"},
                    {name: "chrysler"},
                    {name: "fiat"},
                    {name: "bentley"},
                    {name: "scion"},
                    {name: "audi"},
                    {name: "suzuki"},
                    {name: "ford"},
                    {name: "kia"},
                    {name: "iveco"},
                    {name: "москвич"},
                    {name: "rover"},
                    {name:"opel"},
                    {name:"ssangyong"},
                    {name: "asia"},
                    {name: "nissan"},
                    {name: "volvo"},
                    {name: "maserati"},
                    {name: "smart"},
                    {name: "land rover"},
                    {name: "skoda"},
                    {name: "раф"},
                    {name: "ваз (lada)"},
                    {name: "mini"},
                    {name: "renault"},
                    {name: "jaguar"},
                    {name: "hummer"},
                    {name:"datsun"},
                    {name : "dodge"}]
export default allmarks