import React from "react"
import ReactDOM from "react-dom"
import App from "./components/App"
import "./search-string-style.css"
import "./products-style.css"
import "./app-style.css"
import "./main.css"
import "./card-style.css"
import "./showMore-btn.css"
ReactDOM.render(<App/>,document.getElementById("root"))